name: _error
timestamp: 1576595961
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1576595825
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-1657: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-5690: Menu
  messages:
    system-messages-6555: 'System Messages'
  content:
    system-content-4793: 'Page Content'
  copyright:
    copyright-6846: Copyright
  spacer:
    spacer-6754: Spacer
  branding:
    branding-6222: Branding
  mobile-menu:
    mobile-menu-8434: Mobile-menu
inherit: {  }
