version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1576595825
layout:
  /header/:
    -
      - 'logo-5163 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-3005
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-9473
    -
      - system-content-2362
  /footer/:
    -
      - position-footer
    -
      - 'copyright-7147 40'
      - 'spacer-2353 30'
      - 'branding-6717 30'
  offcanvas:
    -
      - mobile-menu-7886
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
